config/routes.rb
Rails.application.routes.draw do
  resources :skill_types
  resources :skills
  resources :paragons
  resources :klasses do
    resources :builds
  end
  resources :builds
  resources :users

end

app/models/build.rb
class Build < ActiveRecord::Base
  belongs_to :user
  belongs_to :klass
  
  has_many :skills

  self.per_page = 10
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: [:show, :edit, :update, :destroy]
  expose(:klasses, ->{ Klass.all })

  # GET /builds
  # GET /builds.json
  def index
    if params[:klass_id]
      @builds = Build.where(klass_id: params[:klass_id])
                     .paginate(page: params[:page])
    else
      @builds = Build.paginate(page: params[:page])
    end
  end

  # GET /builds/1
  # GET /builds/1.json
  def show
  end

  # GET /builds/new
  def new
    @build = Build.new
  end

  # GET /builds/1/edit
  def edit
  end

  # POST /builds
  # POST /builds.json
  def create
    @build = Build.new(build_params)

    respond_to do |format|
      if @build.save
        format.html { redirect_to @build, notice: 'Build was successfully created.' }
        format.json { render :show, status: :created, location: @build }
      else
        format.html { render :new }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /builds/1
  # PATCH/PUT /builds/1.json
  def update
    respond_to do |format|
      if @build.update(build_params)
        format.html { redirect_to @build, notice: 'Build was successfully updated.' }
        format.json { render :show, status: :ok, location: @build }
      else
        format.html { render :edit }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builds/1
  # DELETE /builds/1.json
  def destroy
    @build.destroy
    respond_to do |format|
      format.html { redirect_to builds_url, notice: 'Build was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build
      @build = Build.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.require(:build).permit(:name, :klass_id)
    end
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/views/builds/_form.html.erb
<%= form_for(@build) do |f| %>
  <% if @build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% @build.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= collection_select(:build, :klass_id, klasses, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/builds/edit.html.erb
<h1>Editing Build</h1>

<%= render 'form' %>

<%= link_to 'Show', @build %> |
<%= link_to 'Back', builds_path %>

app/views/builds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Builds</h1>

<ul class="class-filter">
  <% active_show_all = 'active' if !params[:klass_id].present? %>
  <li class="<%= active_show_all %>"><%= link_to 'Show All', builds_path %></li>
  <% klasses.each do |klass| %>
    <% active_build = 'active' if klass.id.to_s == params[:klass_id].to_s %>
    <li class="<%= active_build %>">
      <%= link_to klass_builds_path(klass) do %>
        <%= image_tag "class_icons/#{klass.name.parameterize}" %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Build', new_build_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <tr>
        <td><%= build.name %></td>
        <td><%= build.klass.name %></td>
        <td><%= link_to 'Show', build %></td>
        <td><%= link_to 'Edit', edit_build_path(build) %></td>
        <td><%= link_to 'Destroy', build, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @builds %>

app/views/builds/new.html.erb
<h1>New Build</h1>

<%= render 'form' %>

<%= link_to 'Back', builds_path %>

app/views/builds/show.html.erb
<p id="notice"><%= notice %></p>

<pre>Last updated <%= time_ago_in_words(@build.updated_at) %> ago</pre>
<p>
  <strong>Name:</strong>
  <%= @build.name %>
</p>

<p>
  <strong>class:</strong>
  <%= @build.klass.name %>
</p>

<%= link_to 'Edit', edit_build_path(@build) %> |
<%= link_to 'Back', builds_path %>