config/routes.rb
Rails.application.routes.draw do
  resources :skill_types
  resources :skills
  resources :paragons
  resources :klasses do
    resources :builds
  end
  resources :builds
  resources :users

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :klass
  belongs_to :skill_type
  belongs_to :paragon
  belongs_to :build
end

app/models/skill_type.rb
class SkillType < ActiveRecord::Base
  belongs_to :klass
  has_many :skills
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name, :klass_id, :paragon, :skill_type_id, :points, :row, :slot)
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= form_for(@skill) do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :klass_id %><br>
    <%= f.text_field :klass_id %>
  </div>
  <div class="field">
    <%= f.label :paragon %><br>
    <%= f.text_field :paragon %>
  </div>
  <div class="field">
    <%= f.label :skill_type_id %><br>
    <%= f.text_field :skill_type_id %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.text_field :points %>
  </div>
  <div class="field">
    <%= f.label :row %><br>
    <%= f.text_field :row %>
  </div>
  <div class="field">
    <%= f.label :slot %><br>
    <%= f.text_field :slot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Skills</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Paragon</th>
      <th>Skill type</th>
      <th>Points</th>
      <th>Row</th>
      <th>Slot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.group_by(&:klass).each do |klass, skills| %>
      <tr><td colspan="9" style="font-weight: bold; font-size: 1.4rem"><%= klass.name %></td></tr>
      <% skills.each do |skill| %>
        <tr>
          <td><%= skill.name %></td>
          <td><%= skill.paragon.name if skill.paragon %></td>
          <td><%= skill.skill_type.name %></td>
          <td><%= skill.points %></td>
          <td><%= skill.row %></td>
          <td><%= skill.slot %></td>
          <td><%= link_to 'Show', skill %></td>
          <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
          <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form' %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<p>
  <strong>Klass:</strong>
  <%= @skill.klass %>
</p>

<p>
  <strong>Paragon:</strong>
  <%= @skill.paragon %>
</p>

<p>
  <strong>Skill type:</strong>
  <%= @skill.skill_type %>
</p>

<p>
  <strong>Points:</strong>
  <%= @skill.points %>
</p>

<p>
  <strong>Row:</strong>
  <%= @skill.row %>
</p>

<p>
  <strong>Slot:</strong>
  <%= @skill.slot %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>